version: "3"
services:
  postgres:
    image: postgres:11.2
    container_name: postgres
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
     - NODE_ENV=production   
     - POSTGRES_DB=CCCC
     - POSTGRES_USER=CCCC
     - POSTGRES_PASSWORD=762ed1aa0f4e44b6ba2c0ac24f1f623b
    volumes:
      - /var/CCCC/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5532:5432"
