apiVersion: v1
kind: Pod
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  containers:
  - name: transmission
    image: linuxserver/transmission
    env:
    - name: PASS
      value: "3"
    - name: USER
      value: e
    - name: PEERPORT
      value: "30002"
    ports:
    - containerPort: 9091
    - containerPort: 30002
    - containerPort: 30002
      protocol: UDP
    volumeMounts:
    - mountPath: /downloads/complete/
      name: transmission-complete
#   - mountPath: /config/torrents/
#     name: transmission-torrents
  volumes:
  - name: transmission-complete
    hostPath:
      path: /complete
# - name: transmission-torrents
#   hostPath:
#     path: /complete/.torrents
