apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv0
spec:
  storageClassName: redis-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/nfs/redis0"
    server: 192.168.1.187
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv1
spec:
  storageClassName: redis-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/nfs/redis1"
    server: 192.168.1.187
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv2
spec:
  storageClassName: redis-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/nfs/redis2"
    server: 192.168.1.187
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv3
spec:
  storageClassName: redis-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/nfs/redis3"
    server: 192.168.1.187
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv4
spec:
  storageClassName: redis-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/nfs/redis4"
    server: 192.168.1.187
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv5
spec:
  storageClassName: redis-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/nfs/redis5"
    server: 192.168.1.187
