events {
    worker_connections  1024;
}
http {
    server {
        listen              443 ssl;
        server_name         r224;
        ssl_certificate     /etc/nginx/ssl/r224.crt;
        ssl_certificate_key /etc/nginx/ssl/r224.key;
        location / {
            return 200 "TLS is enabled";
        }
    }
}
