services:
  ss:
    container_name: cc
    image: tensorflow/tensorflow:latest-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
    volumes:
      - ${PWD}/gpu.py:~/gpu.py
    entrypoint: python3 ~/gpu.py
