# ht_capab=[HT40+]
# ht_capab=[SHORT-GI-40][HT40+][HT40-][DSSS_CCK-40]
# logger_stdout=-1
# logger_stdout_level=0
# logger_syslog=-1
# logger_syslog_level=0
auth_algs=1
channel=6
driver=nl80211
hw_mode=g
ieee80211n=1
ignore_broadcast_ssid=0
interface=wlan0
macaddr_acl=0
rsn_pairwise=CCMP
ssid=ithurtwhenip
wmm_enabled=1
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
wpa_passphrase=88888888
ctrl_interface=/var/run/hostapd
