---
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Taipei
      - USER=e
      - PASS=3
    volumes:
      - ./downloads:/downloads
    ports:
      - 8091:9091
      - 51413:51413
    restart: unless-stopped
