sshpass -p trtrtrt4 ssh -o StrictHostKeyChecking=no ernie@10.1.16.20 "show ethernet-switching table |match ${1}"
sshpass -p trtrtrt4 ssh -o StrictHostKeyChecking=no ernie@10.1.16.22 "show ethernet-switching table |match ${1}"
sshpass -p trtrtrt4 ssh -o StrictHostKeyChecking=no ernie@10.1.16.23 "show ethernet-switching table |match ${1}"
sshpass -p trtrtrt4 ssh -o StrictHostKeyChecking=no ernie@10.1.16.24 "show ethernet-switching table |match ${1}"
sshpass -p trtrtrt4 ssh -o StrictHostKeyChecking=no ernie@10.1.16.25 "show ethernet-switching table |match ${1}"
